platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_install_ios_plugin_pods(ios_application_path = nil)

  pod 'Firebase/Core'
  pod 'Firebase/Database'
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  flutter_install_ios_plugin_pods File.dirname(File.realpath(__FILE__))
end

